gpio/litex: Select IRQ_DOMAIN_HIERARCHY to fix compile issue
When building on OpenRISC this fixes the failure:

    vers/gpio/gpio-litex.c: In function 'litex_gpio_irq_eoi':
    drivers/gpio/gpio-litex.c:242:9: error: implicit declaration of function 'irq_chip_eoi_parent'; did you mean 'irq_chip_pm_put'? [-Werror=implicit-function-declaration]
      242 |         irq_chip_eoi_parent(idata);
	  |         ^~~~~~~~~~~~~~~~~~~
	  |         irq_chip_pm_put
    drivers/gpio/gpio-litex.c: In function 'litex_gpio_irq_set_affinity':
    drivers/gpio/gpio-litex.c:249:18: error: 'struct irq_data' has no member named 'parent_data'
      249 |         if (idata->parent_data)

The irq_chip_eoi_parent api and others are only exported if config
IRQ_DOMAIN_HIERARCHY is selected.  As this is used in the litex gpio
driver select it by default.

Signed-off-by: Stafford Horne <shorne@gmail.com>